// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vitalsService.proto

package grpc.service.vitals;

public interface monitorUseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vitalsService.monitorUse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 MonitorID = 1;</code>
   */
  int getMonitorID();

  /**
   * <code>string MonitorStatus = 2;</code>
   */
  java.lang.String getMonitorStatus();
  /**
   * <code>string MonitorStatus = 2;</code>
   */
  com.google.protobuf.ByteString
      getMonitorStatusBytes();
}
