// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vitalsService.proto

package grpc.service.vitals;

public interface monitorListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vitalsService.monitorList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string DisplayMonitors = 1;</code>
   */
  java.lang.String getDisplayMonitors();
  /**
   * <code>string DisplayMonitors = 1;</code>
   */
  com.google.protobuf.ByteString
      getDisplayMonitorsBytes();
}
