// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vitalsService.proto

package grpc.service.vitals;

/**
 * Protobuf type {@code vitalsService.monitorUse}
 */
public  final class monitorUse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:vitalsService.monitorUse)
    monitorUseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use monitorUse.newBuilder() to construct.
  private monitorUse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private monitorUse() {
    monitorID_ = 0;
    monitorStatus_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private monitorUse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            monitorID_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            monitorStatus_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.service.vitals.vitalsServiceImpl.internal_static_vitalsService_monitorUse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.service.vitals.vitalsServiceImpl.internal_static_vitalsService_monitorUse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.service.vitals.monitorUse.class, grpc.service.vitals.monitorUse.Builder.class);
  }

  public static final int MONITORID_FIELD_NUMBER = 1;
  private int monitorID_;
  /**
   * <code>int32 MonitorID = 1;</code>
   */
  public int getMonitorID() {
    return monitorID_;
  }

  public static final int MONITORSTATUS_FIELD_NUMBER = 2;
  private volatile java.lang.Object monitorStatus_;
  /**
   * <code>string MonitorStatus = 2;</code>
   */
  public java.lang.String getMonitorStatus() {
    java.lang.Object ref = monitorStatus_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      monitorStatus_ = s;
      return s;
    }
  }
  /**
   * <code>string MonitorStatus = 2;</code>
   */
  public com.google.protobuf.ByteString
      getMonitorStatusBytes() {
    java.lang.Object ref = monitorStatus_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      monitorStatus_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (monitorID_ != 0) {
      output.writeInt32(1, monitorID_);
    }
    if (!getMonitorStatusBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, monitorStatus_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (monitorID_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, monitorID_);
    }
    if (!getMonitorStatusBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, monitorStatus_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.service.vitals.monitorUse)) {
      return super.equals(obj);
    }
    grpc.service.vitals.monitorUse other = (grpc.service.vitals.monitorUse) obj;

    boolean result = true;
    result = result && (getMonitorID()
        == other.getMonitorID());
    result = result && getMonitorStatus()
        .equals(other.getMonitorStatus());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MONITORID_FIELD_NUMBER;
    hash = (53 * hash) + getMonitorID();
    hash = (37 * hash) + MONITORSTATUS_FIELD_NUMBER;
    hash = (53 * hash) + getMonitorStatus().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.service.vitals.monitorUse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.service.vitals.monitorUse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.service.vitals.monitorUse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.service.vitals.monitorUse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.service.vitals.monitorUse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.service.vitals.monitorUse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.service.vitals.monitorUse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.service.vitals.monitorUse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.service.vitals.monitorUse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.service.vitals.monitorUse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.service.vitals.monitorUse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.service.vitals.monitorUse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.service.vitals.monitorUse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code vitalsService.monitorUse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:vitalsService.monitorUse)
      grpc.service.vitals.monitorUseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.service.vitals.vitalsServiceImpl.internal_static_vitalsService_monitorUse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.service.vitals.vitalsServiceImpl.internal_static_vitalsService_monitorUse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.service.vitals.monitorUse.class, grpc.service.vitals.monitorUse.Builder.class);
    }

    // Construct using grpc.service.vitals.monitorUse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      monitorID_ = 0;

      monitorStatus_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.service.vitals.vitalsServiceImpl.internal_static_vitalsService_monitorUse_descriptor;
    }

    @java.lang.Override
    public grpc.service.vitals.monitorUse getDefaultInstanceForType() {
      return grpc.service.vitals.monitorUse.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.service.vitals.monitorUse build() {
      grpc.service.vitals.monitorUse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.service.vitals.monitorUse buildPartial() {
      grpc.service.vitals.monitorUse result = new grpc.service.vitals.monitorUse(this);
      result.monitorID_ = monitorID_;
      result.monitorStatus_ = monitorStatus_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.service.vitals.monitorUse) {
        return mergeFrom((grpc.service.vitals.monitorUse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.service.vitals.monitorUse other) {
      if (other == grpc.service.vitals.monitorUse.getDefaultInstance()) return this;
      if (other.getMonitorID() != 0) {
        setMonitorID(other.getMonitorID());
      }
      if (!other.getMonitorStatus().isEmpty()) {
        monitorStatus_ = other.monitorStatus_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.service.vitals.monitorUse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.service.vitals.monitorUse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int monitorID_ ;
    /**
     * <code>int32 MonitorID = 1;</code>
     */
    public int getMonitorID() {
      return monitorID_;
    }
    /**
     * <code>int32 MonitorID = 1;</code>
     */
    public Builder setMonitorID(int value) {
      
      monitorID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 MonitorID = 1;</code>
     */
    public Builder clearMonitorID() {
      
      monitorID_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object monitorStatus_ = "";
    /**
     * <code>string MonitorStatus = 2;</code>
     */
    public java.lang.String getMonitorStatus() {
      java.lang.Object ref = monitorStatus_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        monitorStatus_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string MonitorStatus = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMonitorStatusBytes() {
      java.lang.Object ref = monitorStatus_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        monitorStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string MonitorStatus = 2;</code>
     */
    public Builder setMonitorStatus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      monitorStatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string MonitorStatus = 2;</code>
     */
    public Builder clearMonitorStatus() {
      
      monitorStatus_ = getDefaultInstance().getMonitorStatus();
      onChanged();
      return this;
    }
    /**
     * <code>string MonitorStatus = 2;</code>
     */
    public Builder setMonitorStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      monitorStatus_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:vitalsService.monitorUse)
  }

  // @@protoc_insertion_point(class_scope:vitalsService.monitorUse)
  private static final grpc.service.vitals.monitorUse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.service.vitals.monitorUse();
  }

  public static grpc.service.vitals.monitorUse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<monitorUse>
      PARSER = new com.google.protobuf.AbstractParser<monitorUse>() {
    @java.lang.Override
    public monitorUse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new monitorUse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<monitorUse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<monitorUse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.service.vitals.monitorUse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

