// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vitalsService.proto

package grpc.service.vitals;

public final class vitalsServiceImpl {
  private vitalsServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vitalsService_vitalsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vitalsService_vitalsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vitalsService_vitalsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vitalsService_vitalsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vitalsService_monitorUse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vitalsService_monitorUse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vitalsService_monitorList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vitalsService_monitorList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023vitalsService.proto\022\rvitalsService\"\034\n\r" +
      "vitalsRequest\022\013\n\003VID\030\001 \001(\005\"+\n\016vitalsResp" +
      "onse\022\r\n\005pulse\030\001 \001(\005\022\n\n\002BP\030\002 \001(\t\"6\n\nmonit" +
      "orUse\022\021\n\tMonitorID\030\001 \001(\005\022\025\n\rMonitorStatu" +
      "s\030\002 \001(\t\"&\n\013monitorList\022\027\n\017DisplayMonitor" +
      "s\030\001 \001(\t2\262\001\n\rvitalsService\022L\n\tgetVitals\022\034" +
      ".vitalsService.vitalsRequest\032\035.vitalsSer" +
      "vice.vitalsResponse\"\0000\001\022S\n\024vMonitorAvail" +
      "ability\022\031.vitalsService.monitorUse\032\032.vit" +
      "alsService.monitorList\"\000(\0010\001B*\n\023grpc.ser" +
      "vice.vitalsB\021vitalsServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_vitalsService_vitalsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_vitalsService_vitalsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vitalsService_vitalsRequest_descriptor,
        new java.lang.String[] { "VID", });
    internal_static_vitalsService_vitalsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_vitalsService_vitalsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vitalsService_vitalsResponse_descriptor,
        new java.lang.String[] { "Pulse", "BP", });
    internal_static_vitalsService_monitorUse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_vitalsService_monitorUse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vitalsService_monitorUse_descriptor,
        new java.lang.String[] { "MonitorID", "MonitorStatus", });
    internal_static_vitalsService_monitorList_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_vitalsService_monitorList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vitalsService_monitorList_descriptor,
        new java.lang.String[] { "DisplayMonitors", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
