// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vitalsService.proto

package grpc.service.vitals;

public interface vitalsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vitalsService.vitalsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 VID = 1;</code>
   */
  int getVID();
}
