// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vitalsService.proto

package grpc.service.vitals;

/**
 * Protobuf type {@code vitalsService.vitalsResponse}
 */
public  final class vitalsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:vitalsService.vitalsResponse)
    vitalsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use vitalsResponse.newBuilder() to construct.
  private vitalsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private vitalsResponse() {
    pulse_ = 0;
    bP_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private vitalsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            pulse_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            bP_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.service.vitals.vitalsServiceImpl.internal_static_vitalsService_vitalsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.service.vitals.vitalsServiceImpl.internal_static_vitalsService_vitalsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.service.vitals.vitalsResponse.class, grpc.service.vitals.vitalsResponse.Builder.class);
  }

  public static final int PULSE_FIELD_NUMBER = 1;
  private int pulse_;
  /**
   * <code>int32 pulse = 1;</code>
   */
  public int getPulse() {
    return pulse_;
  }

  public static final int BP_FIELD_NUMBER = 2;
  private volatile java.lang.Object bP_;
  /**
   * <code>string BP = 2;</code>
   */
  public java.lang.String getBP() {
    java.lang.Object ref = bP_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bP_ = s;
      return s;
    }
  }
  /**
   * <code>string BP = 2;</code>
   */
  public com.google.protobuf.ByteString
      getBPBytes() {
    java.lang.Object ref = bP_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bP_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (pulse_ != 0) {
      output.writeInt32(1, pulse_);
    }
    if (!getBPBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, bP_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (pulse_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, pulse_);
    }
    if (!getBPBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, bP_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.service.vitals.vitalsResponse)) {
      return super.equals(obj);
    }
    grpc.service.vitals.vitalsResponse other = (grpc.service.vitals.vitalsResponse) obj;

    boolean result = true;
    result = result && (getPulse()
        == other.getPulse());
    result = result && getBP()
        .equals(other.getBP());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PULSE_FIELD_NUMBER;
    hash = (53 * hash) + getPulse();
    hash = (37 * hash) + BP_FIELD_NUMBER;
    hash = (53 * hash) + getBP().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.service.vitals.vitalsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.service.vitals.vitalsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.service.vitals.vitalsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.service.vitals.vitalsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.service.vitals.vitalsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.service.vitals.vitalsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.service.vitals.vitalsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.service.vitals.vitalsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.service.vitals.vitalsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.service.vitals.vitalsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.service.vitals.vitalsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.service.vitals.vitalsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.service.vitals.vitalsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code vitalsService.vitalsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:vitalsService.vitalsResponse)
      grpc.service.vitals.vitalsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.service.vitals.vitalsServiceImpl.internal_static_vitalsService_vitalsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.service.vitals.vitalsServiceImpl.internal_static_vitalsService_vitalsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.service.vitals.vitalsResponse.class, grpc.service.vitals.vitalsResponse.Builder.class);
    }

    // Construct using grpc.service.vitals.vitalsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      pulse_ = 0;

      bP_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.service.vitals.vitalsServiceImpl.internal_static_vitalsService_vitalsResponse_descriptor;
    }

    @java.lang.Override
    public grpc.service.vitals.vitalsResponse getDefaultInstanceForType() {
      return grpc.service.vitals.vitalsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.service.vitals.vitalsResponse build() {
      grpc.service.vitals.vitalsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.service.vitals.vitalsResponse buildPartial() {
      grpc.service.vitals.vitalsResponse result = new grpc.service.vitals.vitalsResponse(this);
      result.pulse_ = pulse_;
      result.bP_ = bP_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.service.vitals.vitalsResponse) {
        return mergeFrom((grpc.service.vitals.vitalsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.service.vitals.vitalsResponse other) {
      if (other == grpc.service.vitals.vitalsResponse.getDefaultInstance()) return this;
      if (other.getPulse() != 0) {
        setPulse(other.getPulse());
      }
      if (!other.getBP().isEmpty()) {
        bP_ = other.bP_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.service.vitals.vitalsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.service.vitals.vitalsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int pulse_ ;
    /**
     * <code>int32 pulse = 1;</code>
     */
    public int getPulse() {
      return pulse_;
    }
    /**
     * <code>int32 pulse = 1;</code>
     */
    public Builder setPulse(int value) {
      
      pulse_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 pulse = 1;</code>
     */
    public Builder clearPulse() {
      
      pulse_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object bP_ = "";
    /**
     * <code>string BP = 2;</code>
     */
    public java.lang.String getBP() {
      java.lang.Object ref = bP_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bP_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string BP = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBPBytes() {
      java.lang.Object ref = bP_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bP_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string BP = 2;</code>
     */
    public Builder setBP(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bP_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string BP = 2;</code>
     */
    public Builder clearBP() {
      
      bP_ = getDefaultInstance().getBP();
      onChanged();
      return this;
    }
    /**
     * <code>string BP = 2;</code>
     */
    public Builder setBPBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bP_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:vitalsService.vitalsResponse)
  }

  // @@protoc_insertion_point(class_scope:vitalsService.vitalsResponse)
  private static final grpc.service.vitals.vitalsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.service.vitals.vitalsResponse();
  }

  public static grpc.service.vitals.vitalsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<vitalsResponse>
      PARSER = new com.google.protobuf.AbstractParser<vitalsResponse>() {
    @java.lang.Override
    public vitalsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new vitalsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<vitalsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<vitalsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.service.vitals.vitalsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

