// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vitalsService.proto

package grpc.service.vitals;

public interface vitalsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vitalsService.vitalsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 pulse = 1;</code>
   */
  int getPulse();

  /**
   * <code>string BP = 2;</code>
   */
  java.lang.String getBP();
  /**
   * <code>string BP = 2;</code>
   */
  com.google.protobuf.ByteString
      getBPBytes();
}
