// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patientService.proto

package grpc.service.patient;

public interface ConfirmPROrBuilder extends
    // @@protoc_insertion_point(interface_extends:PatientService.ConfirmPR)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Confirmation = 1;</code>
   */
  java.lang.String getConfirmation();
  /**
   * <code>string Confirmation = 1;</code>
   */
  com.google.protobuf.ByteString
      getConfirmationBytes();

  /**
   * <code>int32 RecordSize = 2;</code>
   */
  int getRecordSize();
}
