// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patientService.proto

package grpc.service.patient;

public final class PatientServiceImpl {
  private PatientServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PatientService_PatientIDRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PatientService_PatientIDRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PatientService_PatientIDResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PatientService_PatientIDResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PatientService_UploadPR_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PatientService_UploadPR_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PatientService_ConfirmPR_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PatientService_ConfirmPR_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024patientService.proto\022\016PatientService\"0" +
      "\n\020PatientIDRequest\022\r\n\005fName\030\001 \001(\t\022\r\n\005lNa" +
      "me\030\002 \001(\t\"&\n\021PatientIDResponse\022\021\n\tPatient" +
      "ID\030\001 \001(\t\"!\n\010UploadPR\022\025\n\rPatientRecord\030\001 " +
      "\001(\t\"5\n\tConfirmPR\022\024\n\014Confirmation\030\001 \001(\t\022\022" +
      "\n\nRecordSize\030\002 \001(\0052\260\001\n\016PatientService\022T\n" +
      "\013generatePID\022 .PatientService.PatientIDR" +
      "equest\032!.PatientService.PatientIDRespons" +
      "e\"\000\022H\n\rpatientRecord\022\030.PatientService.Up" +
      "loadPR\032\031.PatientService.ConfirmPR\"\000(\001B,\n" +
      "\024grpc.service.patientB\022PatientServiceImp" +
      "lP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PatientService_PatientIDRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PatientService_PatientIDRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PatientService_PatientIDRequest_descriptor,
        new java.lang.String[] { "FName", "LName", });
    internal_static_PatientService_PatientIDResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PatientService_PatientIDResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PatientService_PatientIDResponse_descriptor,
        new java.lang.String[] { "PatientID", });
    internal_static_PatientService_UploadPR_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PatientService_UploadPR_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PatientService_UploadPR_descriptor,
        new java.lang.String[] { "PatientRecord", });
    internal_static_PatientService_ConfirmPR_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_PatientService_ConfirmPR_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PatientService_ConfirmPR_descriptor,
        new java.lang.String[] { "Confirmation", "RecordSize", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
