// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patientService.proto

package grpc.service.patient;

public interface PatientIDResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PatientService.PatientIDResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string PatientID = 1;</code>
   */
  java.lang.String getPatientID();
  /**
   * <code>string PatientID = 1;</code>
   */
  com.google.protobuf.ByteString
      getPatientIDBytes();
}
