// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patientService.proto

package grpc.service.patient;

public interface PatientIDRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PatientService.PatientIDRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string fName = 1;</code>
   */
  java.lang.String getFName();
  /**
   * <code>string fName = 1;</code>
   */
  com.google.protobuf.ByteString
      getFNameBytes();

  /**
   * <code>string lName = 2;</code>
   */
  java.lang.String getLName();
  /**
   * <code>string lName = 2;</code>
   */
  com.google.protobuf.ByteString
      getLNameBytes();
}
