// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patientService.proto

package grpc.service.patient;

public interface UploadPROrBuilder extends
    // @@protoc_insertion_point(interface_extends:PatientService.UploadPR)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string PatientRecord = 1;</code>
   */
  java.lang.String getPatientRecord();
  /**
   * <code>string PatientRecord = 1;</code>
   */
  com.google.protobuf.ByteString
      getPatientRecordBytes();
}
